language: scala
jdk: oraclejdk8
scala:
- 2.12.8
script:
- sbt ++$TRAVIS_SCALA_VERSION test
deploy:
  provider: heroku
  api_key:
    secure: gZeBWtFjkBe2ccC/T1GncLAi62ShwhKnzKUKo4Z01qbqGyPXmgmtMV/1Zno/csVeqosarzfEgIkNhRs0Xm/OPPy0R527KGbN87g0dvYE3o3k037DAG2/9CaqgWIr/iy5vty7NTSiHshIErGEnPZf4rK35A0JNegcmKZmBcqyEyFd69RSIL1gQ8d8WmQqrp2uzpvW2LAoBKbsRr0JEZwunZWdkS29V0BjTHOwS3lbm6GOfssVSGcfTazs9GakI4kysJzrJGiny+jO7K4aF9ka5A6WB+T39CttdZc2DFMvSYkteNtYIKcbR1QEFxCR588mNGKJw+onJEiYq+062ayrTCnS85OCZaABFDFW5AKitFkf4ZWqMveN2YYKvqQkczMijBvYxUGpLt/VmTHMd9crlslUzDY1gIQwSI2MSo8a1q8Jq6X16U/zLYX8YmC7GlnZ0w4rTxxDoBHSd0TsnGGVHEjNRFRB9rLUEsbN9hZk65cNWX9rZqTBB6svty7g5qoOdqPu2h/DuGQdkH95q5dOeUhI0r2seK4kIdUhRyB/XdmOs+z/SOUN0jhzi7D6pupSIqw5BW+rnjSNNV/6d8A4pbEQD8fRo9dVMAcPOQk9zGnc5gA3J5qCOZ6fYp/zZJG2VdmS9BD38dvmLeYG5NtXLdk95tdjyMZ9EiMJ2qrBvGU=
  app: chord-dht
  on:
    repo: denis631/chord-dht
